export type FeatureSlug = 'connections' | 'polycule-map' | 'wellness' | 'reflection' | 'insights' | 'vio' | 'safe-call' | 'notifications' | 'vibe-radar';
export type Lang = 'de' | 'en' | 'nl' | 'es' | 'da' | 'sv';

export const featureSlugs: FeatureSlug[] = [
  'connections', 'polycule-map', 'wellness', 'reflection', 'insights', 'vio', 'safe-call', 'notifications', 'vibe-radar',
];

export interface FeatureContent {
  name: string;
  shortDesc: string;
  longDesc: string;
  bullets?: string[];
  vio?: true;
  icon?: string;
}

const iconConnections = `<svg width="48" height="48" viewBox="0 0 34 34" fill="none" xmlns="http://www.w3.org/2000/svg"><circle cx="12" cy="13" r="5" stroke="#8b5cf6" stroke-width="2"/><path d="M3 28c0-4.418 4.03-8 9-8s9 3.582 9 8" stroke="#8b5cf6" stroke-width="2" stroke-linecap="round"/><circle cx="25" cy="11" r="4" stroke="#c4b5fd" stroke-width="1.75"/><path d="M20 26c0-3.314 2.686-6 6-6" stroke="#c4b5fd" stroke-width="1.75" stroke-linecap="round"/></svg>`;
const iconPolyculeMap = `<svg width="48" height="48" viewBox="0 0 34 34" fill="none" xmlns="http://www.w3.org/2000/svg"><circle cx="17" cy="17" r="4" fill="#8b5cf6"/><circle cx="6" cy="9" r="3" stroke="#8b5cf6" stroke-width="1.75"/><circle cx="28" cy="9" r="3" stroke="#c4b5fd" stroke-width="1.75"/><circle cx="6" cy="25" r="3" stroke="#4fd6c2" stroke-width="1.75"/><circle cx="28" cy="25" r="3" stroke="#f0789f" stroke-width="1.75"/><line x1="17" y1="17" x2="6" y2="9" stroke="#8b5cf6" stroke-width="1.5" stroke-opacity="0.6"/><line x1="17" y1="17" x2="28" y2="9" stroke="#c4b5fd" stroke-width="1.5" stroke-opacity="0.6"/><line x1="17" y1="17" x2="6" y2="25" stroke="#4fd6c2" stroke-width="1.5" stroke-opacity="0.6"/><line x1="17" y1="17" x2="28" y2="25" stroke="#f0789f" stroke-width="1.5" stroke-opacity="0.6"/></svg>`;
const iconWellness = `<svg width="48" height="48" viewBox="0 0 34 34" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M17 29C17 29 5 22 5 13a7 7 0 0 1 12-4.9A7 7 0 0 1 29 13c0 9-12 16-12 16z" stroke="#8b5cf6" stroke-width="2" stroke-linejoin="round"/><path d="M12 17l3 3 6-6" stroke="#c4b5fd" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
const iconReflection = `<svg width="48" height="48" viewBox="0 0 34 34" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="6" y="5" width="16" height="24" rx="3" stroke="#8b5cf6" stroke-width="2"/><path d="M22 8h3a3 3 0 0 1 3 3v13a3 3 0 0 1-3 3h-3" stroke="#c4b5fd" stroke-width="1.75"/><line x1="10" y1="11" x2="18" y2="11" stroke="#8b5cf6" stroke-width="1.75" stroke-linecap="round"/><line x1="10" y1="16" x2="18" y2="16" stroke="#8b5cf6" stroke-width="1.75" stroke-linecap="round"/><line x1="10" y1="21" x2="15" y2="21" stroke="#8b5cf6" stroke-width="1.75" stroke-linecap="round"/></svg>`;
const iconInsights = `<svg width="48" height="48" viewBox="0 0 34 34" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M5 24l7-7 5 4 8-10 4 4" stroke="#8b5cf6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><circle cx="12" cy="17" r="2.5" fill="#8b5cf6"/><circle cx="17" cy="21" r="2.5" fill="#c4b5fd"/><circle cx="25" cy="11" r="2.5" fill="#8b5cf6"/><line x1="5" y1="28" x2="29" y2="28" stroke="#2a2833" stroke-width="1.5"/></svg>`;
const iconSafeCall = `<svg width="48" height="48" viewBox="0 0 34 34" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M17 4L6 8.5V17c0 6 4.925 11.5 11 12.8C23.075 28.5 28 23 28 17V8.5L17 4z" stroke="#8b5cf6" stroke-width="2" stroke-linejoin="round"/><path d="M12 17l3 3 6-6" stroke="#c4b5fd" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
const iconNotifications = `<svg width="48" height="48" viewBox="0 0 34 34" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M17 5a7 7 0 0 0-7 7v5l-2 3h18l-2-3v-5a7 7 0 0 0-7-7z" stroke="#8b5cf6" stroke-width="2" stroke-linejoin="round"/><path d="M14 23a3 3 0 0 0 6 0" stroke="#c4b5fd" stroke-width="1.75"/><circle cx="17" cy="5" r="1.5" fill="#8b5cf6"/></svg>`;
const iconVibeRadar = `<svg width="48" height="48" viewBox="0 0 34 34" fill="none" xmlns="http://www.w3.org/2000/svg"><circle cx="17" cy="17" r="3" fill="#8b5cf6"/><path d="M11.5 11.5a7.8 7.8 0 0 0 0 11" stroke="#8b5cf6" stroke-width="1.75" stroke-linecap="round"/><path d="M22.5 11.5a7.8 7.8 0 0 1 0 11" stroke="#8b5cf6" stroke-width="1.75" stroke-linecap="round"/><path d="M7 7a14 14 0 0 0 0 19.8" stroke="#c4b5fd" stroke-width="1.5" stroke-linecap="round"/><path d="M27 7a14 14 0 0 1 0 19.8" stroke="#c4b5fd" stroke-width="1.5" stroke-linecap="round"/></svg>`;

export const featureScreenshots: Record<FeatureSlug, string | null> = {
  connections: '/roster-screenshots/Verbindungen.PNG',
  'polycule-map': '/roster-screenshots/Polycule map.PNG',
  wellness: '/roster-screenshots/wellness.PNG',
  reflection: '/roster-screenshots/reflexion.PNG',
  insights: '/roster-screenshots/Insights.PNG',
  vio: '/roster-screenshots/Vio.PNG',
  'safe-call': null,
  notifications: null,
  'vibe-radar': null,
};

export const featureIcons: Record<FeatureSlug, string | null> = {
  connections: iconConnections,
  'polycule-map': iconPolyculeMap,
  wellness: iconWellness,
  reflection: iconReflection,
  insights: iconInsights,
  vio: null,
  'safe-call': iconSafeCall,
  notifications: iconNotifications,
  'vibe-radar': iconVibeRadar,
};

export const featureData: Record<Lang, Record<FeatureSlug, FeatureContent>> = {
  de: {
    connections: {
      name: 'Verbindungen',
      shortDesc: 'Alle deine Beziehungen an einem Ort – mit Beziehungstyp, Schutzstatus und einem schnellen Kontakt-Log.',
      longDesc: 'Alle wichtigen Menschen an einem Ort. Für jede Verbindung hinterlegst du Beziehungstyp, Safer-Sex-Status und kurze Notizen nach Treffen – alles lokal auf deinem Gerät, nichts in der Cloud.',
      bullets: [
        'Personen-Grid mit Foto oder Initialen und Vibe-Indikator',
        'Personalisierter Begrüßungs-Header – tageszeitabhängig',
        'Suchfeld und FAB zum schnellen Hinzufügen',
        'Wisch-Geste: Kontakt als „heute gehabt" loggen',
        'Favoriten-Markierung für deine engsten Verbindungen',
      ],
      icon: iconConnections,
    },
    'polycule-map': {
      name: 'Polycule Map',
      shortDesc: 'Dein Beziehungsnetz als lebendige Karte. Du im Zentrum, alle Verbindungen drumherum, nach Typ farbcodiert.',
      longDesc: 'Sieh dein Netz auf einen Blick. Die Polycule Map visualisiert alle deine Verbindungen als interaktive Karte – du im Zentrum, deine Partner·innen und Metamours drumherum, farblich nach Beziehungstyp unterschieden.',
      bullets: [
        'Ego-Netzwerk mit konzentrischen Ringen',
        'Innerer Ring: enge Verbindungen – äußerer Ring: lockere',
        'Peer-Bögen für Querverbindungen wie Metamour-Beziehungen',
        'Nativer PanZoom mit Pinch-to-Zoom-Gesten',
        'Tippbare Kanten zeigen den jeweiligen Verbindungstyp',
      ],
      icon: iconPolyculeMap,
    },
    wellness: {
      name: 'Wellness',
      shortDesc: 'Behalte STI-Tests und Check-ins im Blick – diskret, lokal, ohne dass es jemand außer dir sieht.',
      longDesc: 'Diskrete Gesundheits-Notizen für verantwortungsvolle Beziehungsführung. Du kannst STI-Tests, Safer-Sex-Gespräche und Health-Check-ins eintragen – verschlüsselt auf deinem Gerät, unsichtbar für alle außer dir.',
      bullets: [
        'STI-Tests und Health-Check-Ins protokollieren',
        'Nächster fälliger Test mit automatischem Reminder',
        'Chronologische Timeline aller Einträge',
        'Personen-Filter: alle oder eine einzelne Person',
        'Deep-Link aus Notifications direkt zum Check-In',
      ],
      icon: iconWellness,
    },
    reflection: {
      name: 'Reflexion',
      shortDesc: 'Ein Journal für Eifersucht, Compersion und alles dazwischen. Zum Sortieren, nicht zum Bewerten.',
      longDesc: 'Ein Journal für alles, was du nicht sofort in Worte fassen kannst. Eifersucht, Compersion, Verwirrung – hier darf es einfach da sein, ohne Bewertung und ohne Algorithmus.',
      bullets: [
        'Dekompressions-Einträge, nach Datum sortiert',
        'Detail- und Bearbeitungs-View pro Eintrag',
        'Optionale Verknüpfung mit einer Person',
        'Kein Scoring, keine Bewertung – nur Raum',
      ],
      icon: iconReflection,
    },
    insights: {
      name: 'Insights',
      shortDesc: 'Sanfte Muster statt kalter Zahlen: Wo investierst du Energie, wo wird es gerade still?',
      longDesc: 'Weiche Muster statt harter Zahlen. Insights zeigt dir, wo du zuletzt Energie investiert hast und wo es ruhiger wurde – kein Scoring, keine Bewertung, nur ehrliche Beobachtungen.',
      bullets: [
        'Wochen-Überblick mit Auto-Reset jeden Montag',
        'Klickbare Insights mit persönlichem Bezug zu Personen',
        'Vio-Karte integriert (wenn Vio aktiviert)',
        'Keine Scores oder Ratings – nur Beobachtungen',
      ],
      icon: iconInsights,
    },
    vio: {
      name: 'Vio',
      shortDesc: 'Dein kleiner Begleiter, der nachfragt wie es dir geht – mal sanft, mal locker, mal schonungslos ehrlich.',
      longDesc: 'Vio ist deine KI-Begleitfigur, die täglich kurz nachfragt, wie es dir geht. Der Ton passt sich an: manchmal locker, manchmal nachdenklich tief. Alles bleibt auf deinem Gerät – Vio erinnert sich an nichts.',
      bullets: [
        'Gesprächsfluss: Intro → Highlights → Sorgen → Outro',
        'Tonalität wählbar: locker / sanft / schonungslos (Premium)',
        'Wöchentliche Insights-Karte mit persönlichem Überblick',
        'VioRoast: datenbasierter Roast deiner Woche (Premium)',
        'TTS-Stimme lokal auf deinem Gerät (Premium)',
      ],
      vio: true,
    },
    'safe-call': {
      name: 'Safe-Call',
      shortDesc: 'Leg vorher fest, wer eingreift – und eine Deadline, bis wann du dich meldest.',
      longDesc: 'Ein diskretes Sicherheitsnetz für Treffen mit neuen Menschen. Du wählst eine Vertrauensperson, setzt eine Check-In-Deadline und Roster erinnert diskret – ohne Aufsehen, ohne Drama.',
      bullets: [
        'Person und Trusted Contact aus dem Adressbuch wählen',
        'Check-In-Deadline mit Datum und Uhrzeit festlegen',
        'Aktiver Countdown während der laufenden Session',
        'Diskrete Benachrichtigung wenn die Deadline abläuft',
        'One-Tap-Notrufvorbereitung an den Trusted Contact',
      ],
      icon: iconSafeCall,
    },
    notifications: {
      name: 'Benachrichtigungen',
      shortDesc: 'Diskrete Erinnerungen, die wissen wann sie erscheinen sollen – und wann nicht.',
      longDesc: 'Roster schickt dir Hinweise genau dann, wenn sie hilfreich sind: wenn ein STI-Test fällig wird, eine Safe-Call-Deadline abläuft oder eine Verbindung schon länger still war. Alles lokal, kein Push-Server.',
      bullets: [
        'Diskreter Pulse-Check wenn eine Verbindung schon länger still ist',
        'Wellness-Erinnerung wenn ein Test fällig wird',
        'Safe-Call-Deadline-Reminder kurz vor Ablauf',
        'Deep-Link direkt zur relevanten Ansicht in der App',
        '100 % lokal – kein Push-Server, kein Backend',
      ],
      icon: iconNotifications,
    },
    'vibe-radar': {
      name: 'Vibe-Radar',
      shortDesc: 'Ein ruhiger Indikator pro Verbindung – erkennst du auf einen Blick, wer gerade Aufmerksamkeit braucht.',
      longDesc: 'Der Vibe-Radar berechnet für jede Verbindung einen leisen Status – sonnig, bewölkt, regnerisch oder Funkstille – basierend auf Rhythmus, letztem Kontakt und deiner eigenen Einschätzung. Kein Scoring, nur ein ehrlicher Blick.',
      bullets: [
        'Vier Status-Stufen: sonnig / bewölkt / regnerisch / Funkstille',
        'Basiert auf Rhythmus, letztem Kontakt und Vibe-Qualität',
        'Individuell einstellbare Sensitivität pro Person',
        'Global an- und ausschaltbar',
        'Erscheint direkt im Personen-Grid als dezenter Indikator',
      ],
      icon: iconVibeRadar,
    },
  },
  en: {
    connections: {
      name: 'Connections',
      shortDesc: 'Every relationship in one place — with type, protection status and a quick contact log.',
      longDesc: 'Every important person, in one place. For each connection you can set a relationship type, safer-sex status and quick contact notes — all local on your device, nothing in the cloud.',
      bullets: [
        'People grid with photo or initials and a vibe indicator',
        'Personalised greeting header — adapts to time of day',
        'Search field and FAB to quickly add new people',
        'Swipe gesture to log a contact as "seen today"',
        'Favourite flag for your closest connections',
      ],
      icon: iconConnections,
    },
    'polycule-map': {
      name: 'Polycule Map',
      shortDesc: 'Your relationship web as a living map. You at the centre, every connection colour-coded by type.',
      longDesc: 'See your network at a glance. The Polycule Map renders all your connections as an interactive graph — you at the centre, partners and metamours around you, colour-coded by relationship type.',
      bullets: [
        'Ego-network with concentric rings',
        'Inner ring: close connections – outer ring: lighter ones',
        'Peer arcs for cross-connections like metamour relationships',
        'Native pan-zoom with pinch-to-zoom gestures',
        'Tappable edges reveal the connection type',
      ],
      icon: iconPolyculeMap,
    },
    wellness: {
      name: 'Wellness',
      shortDesc: 'Keep STI tests and check-ins in view — discreet, local, seen by no one but you.',
      longDesc: 'Discreet health notes for responsible relationship care. Log STI tests, safer-sex conversations and check-ins — encrypted on your device, invisible to everyone but you.',
      bullets: [
        'Log STI tests and health check-ins',
        'Next due test with automatic reminder',
        'Chronological timeline of all entries',
        'People filter: all or a single person',
        'Deep-link from notifications straight to the check-in',
      ],
      icon: iconWellness,
    },
    reflection: {
      name: 'Reflection',
      shortDesc: 'A journal for jealousy, compersion and everything between. To sort, not to judge.',
      longDesc: 'A journal for everything you can\'t put into words just yet. Jealousy, compersion, confusion — let it all be here without judgement and without an algorithm sorting it for you.',
      bullets: [
        'Decompression entries sorted by date',
        'Detail and edit view per entry',
        'Optional link to a specific person',
        'No scoring, no algorithm — just space',
      ],
      icon: iconReflection,
    },
    insights: {
      name: 'Insights',
      shortDesc: 'Gentle patterns over cold numbers: where you invest energy, where things go quiet.',
      longDesc: 'Soft patterns instead of hard numbers. Insights shows where you\'ve been investing energy lately and where things have grown quieter — no scoring, no ratings, just honest observations.',
      bullets: [
        'Weekly overview that auto-resets every Monday',
        'Clickable insights with personal links to people',
        'Vio card integrated (when Vio is enabled)',
        'No scores or ratings — only observations',
      ],
      icon: iconInsights,
    },
    vio: {
      name: 'Vio',
      shortDesc: 'Your little companion who checks in on you — gentle, casual, or brutally honest.',
      longDesc: 'Vio is your AI companion who checks in with you every day. The tone adapts: sometimes breezy, sometimes deeper. Everything stays on your device — Vio remembers nothing.',
      bullets: [
        'Conversation flow: intro → highlights → worries → outro',
        'Tone selector: casual / gentle / brutally honest (Premium)',
        'Weekly insights card with a personal overview',
        'VioRoast: data-based roast of your week (Premium)',
        'Local TTS voice on your device (Premium)',
      ],
      vio: true,
    },
    'safe-call': {
      name: 'Safe Call',
      shortDesc: 'Set who steps in beforehand — and a deadline by which you check in.',
      longDesc: 'A discreet safety net for meeting new people. Pick a trusted contact, set a check-in deadline, and Roster nudges discreetly if you go quiet — no fuss, no drama.',
      bullets: [
        'Pick a person and a trusted contact from your address book',
        'Set a check-in deadline with date and time',
        'Live countdown during an active session',
        'Discreet notification when the deadline passes',
        'One-tap emergency prep message to your trusted contact',
      ],
      icon: iconSafeCall,
    },
    notifications: {
      name: 'Notifications',
      shortDesc: 'Discreet reminders that know when to show up — and when not to.',
      longDesc: 'Roster nudges you exactly when it\'s helpful: when an STI test is due, a safe-call deadline is approaching, or a connection has gone quiet for a while. All local, no push server.',
      bullets: [
        'Discreet pulse-check when a connection has been quiet too long',
        'Wellness reminder when a test becomes due',
        'Safe-call deadline reminder shortly before it expires',
        'Deep-link straight to the relevant view in the app',
        '100 % local — no push server, no backend',
      ],
      icon: iconNotifications,
    },
    'vibe-radar': {
      name: 'Vibe Radar',
      shortDesc: 'A quiet indicator per connection — see at a glance who needs attention right now.',
      longDesc: 'The Vibe Radar calculates a gentle status for each connection — sunny, cloudy, rainy or radio silence — based on rhythm, last contact and your own assessment. No scoring, just an honest look.',
      bullets: [
        'Four status levels: sunny / cloudy / rainy / radio silence',
        'Based on rhythm, last contact and vibe quality',
        'Individually adjustable sensitivity per person',
        'Can be toggled on and off globally',
        'Shows as a subtle indicator directly in the people grid',
      ],
      icon: iconVibeRadar,
    },
  },
  nl: {
    connections: {
      name: 'Verbindingen',
      shortDesc: 'Al je relaties op één plek – met relatietype, beschermingsstatus en een snelle contactlog.',
      longDesc: 'Alle belangrijke mensen op één plek. Voor elke verbinding stel je het relatietype, veiligheidsstatus en korte notities in — alles lokaal op je apparaat, niets in de cloud.',
      bullets: [
        'Personenraster met foto of initialen en vibe-indicator',
        'Persoonlijke begroeting – past zich aan op het tijdstip',
        'Zoekveld en FAB om snel mensen toe te voegen',
        'Veeggebaar om contact te loggen als "vandaag gehad"',
        'Favorieten voor je nauwste verbindingen',
      ],
      icon: iconConnections,
    },
    'polycule-map': {
      name: 'Polycule Map',
      shortDesc: 'Je relatienetwerk als een levende kaart. Jij in het centrum, alle verbindingen eromheen, kleurgecodeerd.',
      longDesc: 'Zie je netwerk in één oogopslag. De Polycule Map toont al je verbindingen als een interactieve grafiek — jij in het centrum, partners en metamours eromheen, kleurgecodeerd op relatietype.',
      bullets: [
        'Ego-netwerk met concentrische ringen',
        'Binnenste ring: nauwe verbindingen – buitenste: lossere',
        'Peer-bogen voor dwarsverbindingen zoals metamour-relaties',
        'Natieve pan-zoom met knijpgebaren',
        'Tik op een lijn om het verbindingstype te zien',
      ],
      icon: iconPolyculeMap,
    },
    wellness: {
      name: 'Wellness',
      shortDesc: 'Houd soa-tests en check-ins bij – discreet, lokaal, onzichtbaar voor iedereen behalve jij.',
      longDesc: 'Discrete gezondheidsnotities voor verantwoorde relatievoering. Leg soa-tests, safer-sex-gesprekken en check-ins vast — versleuteld op je apparaat, onzichtbaar voor iedereen behalve jij.',
      bullets: [
        'Soa-tests en gezondheidschecks vastleggen',
        'Volgende verschuldigde test met automatische herinnering',
        'Chronologische tijdlijn van alle vermeldingen',
        'Personenfilter: iedereen of één persoon',
        'Deeplink vanuit meldingen direct naar de check-in',
      ],
      icon: iconWellness,
    },
    reflection: {
      name: 'Reflectie',
      shortDesc: 'Een dagboek voor jaloezie, compersion en alles daartussenin. Om te sorteren, niet om te oordelen.',
      longDesc: 'Een dagboek voor alles wat je nog niet onder woorden kunt brengen. Jaloezie, compersion, verwarring — laat het er allemaal zijn, zonder oordeel en zonder algoritme.',
      bullets: [
        'Decompressie-vermeldingen gesorteerd op datum',
        'Detail- en bewerkingsweergave per vermelding',
        'Optionele koppeling aan een persoon',
        'Geen scores, geen algoritme – alleen ruimte',
      ],
      icon: iconReflection,
    },
    insights: {
      name: 'Inzichten',
      shortDesc: 'Zachte patronen in plaats van koude cijfers: waar investeer je energie, waar wordt het stil?',
      longDesc: 'Zachte patronen in plaats van harde cijfers. Inzichten laat zien waar je energie naartoe gaat en waar het stiller is geworden — geen scores, geen beoordelingen, alleen eerlijke observaties.',
      bullets: [
        'Weekoverzicht dat elke maandag automatisch reset',
        'Klikbare inzichten met persoonlijke koppeling aan mensen',
        'Vio-kaart geïntegreerd (als Vio actief is)',
        'Geen scores of beoordelingen – alleen observaties',
      ],
      icon: iconInsights,
    },
    vio: {
      name: 'Vio',
      shortDesc: 'Je kleine metgezel die vraagt hoe het gaat – soms zacht, soms luchtig, soms brutaal eerlijk.',
      longDesc: 'Vio is je AI-metgezel die elke dag even vraagt hoe het gaat. De toon past zich aan: soms luchtig, soms dieper. Alles blijft op je apparaat — Vio onthoudt niets.',
      bullets: [
        'Gespreksstroom: intro → hoogtepunten → zorgen → outro',
        'Toonkeuze: luchtig / zacht / bikkelhard eerlijk (Premium)',
        'Wekelijkse inzichtenkaart met persoonlijk overzicht',
        'VioRoast: datagestuurde roast van je week (Premium)',
        'Lokale TTS-stem op je apparaat (Premium)',
      ],
      vio: true,
    },
    'safe-call': {
      name: 'Veiligheidsoproep',
      shortDesc: 'Stel van tevoren in wie ingrijpt – en een deadline waarbinnen je incheckt.',
      longDesc: 'Een discreet veiligheidsnet voor ontmoetingen met nieuwe mensen. Kies een vertrouwd contact, stel een incheckdeadline in en Roster herinnert je discreet als je stil blijft — geen ophef, geen drama.',
      bullets: [
        'Kies een persoon en vertrouwd contact uit je adresboek',
        'Stel een incheckdeadline in met datum en tijd',
        'Actieve aftelling tijdens een lopende sessie',
        'Discrete melding wanneer de deadline verstrijkt',
        'Noodvoorbereiding met één tik naar je vertrouwde contact',
      ],
      icon: iconSafeCall,
    },
    notifications: {
      name: 'Meldingen',
      shortDesc: 'Discrete herinneringen die weten wanneer ze moeten verschijnen – en wanneer niet.',
      longDesc: 'Roster herinnert je precies wanneer het nuttig is: als een soa-test verschuldigd is, een veiligheidsdeadline nadert of een verbinding al een tijdje stil is. Alles lokaal, geen pushserver.',
      bullets: [
        'Discrete check wanneer een verbinding te lang stil is geweest',
        'Welzijnsherinnering als een test verschuldigd wordt',
        'Veiligheidsoproep-deadline-herinnering vlak voor het verstrijken',
        'Deeplink direct naar de relevante weergave in de app',
        '100% lokaal – geen pushserver, geen backend',
      ],
      icon: iconNotifications,
    },
    'vibe-radar': {
      name: 'Vibe-Radar',
      shortDesc: 'Een subtiele indicator per verbinding – zie in één oogopslag wie aandacht nodig heeft.',
      longDesc: 'De Vibe-Radar berekent voor elke verbinding een rustige status — zonnig, bewolkt, regenachtig of radiostilte — gebaseerd op ritme, laatste contact en je eigen inschatting. Geen scores, alleen een eerlijke blik.',
      bullets: [
        'Vier statusniveaus: zonnig / bewolkt / regenachtig / radiostilte',
        'Gebaseerd op ritme, laatste contact en vibe-kwaliteit',
        'Individueel instelbare gevoeligheid per persoon',
        'Globaal aan- en uitzetten',
        'Verschijnt als subtiele indicator direct in het personenraster',
      ],
      icon: iconVibeRadar,
    },
  },
  es: {
    connections: {
      name: 'Conexiones',
      shortDesc: 'Todas tus relaciones en un solo lugar – con tipo, estado de protección y un registro rápido.',
      longDesc: 'Todas las personas importantes en un solo lugar. Para cada conexión puedes establecer tipo de relación, estado de sexo seguro y notas rápidas — todo local en tu dispositivo, nada en la nube.',
      bullets: [
        'Cuadrícula de personas con foto o iniciales e indicador de vibra',
        'Saludo personalizado que se adapta a la hora del día',
        'Campo de búsqueda y botón flotante para añadir personas',
        'Gesto deslizante para registrar contacto como "visto hoy"',
        'Marcado de favoritos para tus conexiones más cercanas',
      ],
      icon: iconConnections,
    },
    'polycule-map': {
      name: 'Mapa Polycule',
      shortDesc: 'Tu red de relaciones como un mapa vivo. Tú en el centro, todas las conexiones a tu alrededor.',
      longDesc: 'Ve tu red de un vistazo. El Mapa Polycule muestra todas tus conexiones como un grafo interactivo — tú en el centro, parejas y metamors a tu alrededor, con código de colores por tipo de relación.',
      bullets: [
        'Ego-red con anillos concéntricos',
        'Anillo interior: conexiones cercanas – exterior: más laxas',
        'Arcos entre pares para relaciones cruzadas como metamors',
        'Pan-zoom nativo con gestos de pellizco',
        'Toca una línea para ver el tipo de conexión',
      ],
      icon: iconPolyculeMap,
    },
    wellness: {
      name: 'Bienestar',
      shortDesc: 'Mantén los controles de ITS y check-ins a la vista – discreto, local, invisible para todos menos tú.',
      longDesc: 'Notas de salud discretas para relaciones responsables. Registra pruebas de ITS, conversaciones de sexo seguro y check-ins — cifrado en tu dispositivo, invisible para todos menos tú.',
      bullets: [
        'Registrar pruebas de ITS y chequeos de salud',
        'Próxima prueba con recordatorio automático',
        'Línea de tiempo cronológica de todas las entradas',
        'Filtro por persona: todas o una en concreto',
        'Deep-link desde notificaciones directo al check-in',
      ],
      icon: iconWellness,
    },
    reflection: {
      name: 'Reflexión',
      shortDesc: 'Un diario para los celos, la compersión y todo lo que hay en medio. Para ordenar, no para juzgar.',
      longDesc: 'Un diario para todo lo que no puedes poner en palabras todavía. Celos, compersión, confusión — deja que todo esté aquí, sin juicios y sin que un algoritmo lo clasifique por ti.',
      bullets: [
        'Entradas de descompresión ordenadas por fecha',
        'Vista de detalle y edición por entrada',
        'Enlace opcional a una persona específica',
        'Sin puntuaciones ni algoritmos — solo espacio',
      ],
      icon: iconReflection,
    },
    insights: {
      name: 'Perspectivas',
      shortDesc: 'Patrones suaves en lugar de números fríos: ¿dónde inviertes energía, dónde se hace el silencio?',
      longDesc: 'Patrones suaves en lugar de números fríos. Perspectivas te muestra dónde has estado invirtiendo energía y dónde las cosas se han calmado — sin puntuaciones, solo observaciones honestas.',
      bullets: [
        'Resumen semanal con reinicio automático cada lunes',
        'Perspectivas clicables con vínculos personales a personas',
        'Tarjeta de Vio integrada (si Vio está activo)',
        'Sin puntuaciones ni valoraciones — solo observaciones',
      ],
      icon: iconInsights,
    },
    vio: {
      name: 'Vio',
      shortDesc: 'Tu pequeño compañero que pregunta cómo estás – a veces suave, a veces casual, a veces brutalmente honesto.',
      longDesc: 'Vio es tu compañero de IA que se registra contigo cada día. El tono se adapta: a veces ligero, a veces más profundo. Todo se queda en tu dispositivo — Vio no recuerda nada.',
      bullets: [
        'Flujo de conversación: intro → momentos clave → preocupaciones → outro',
        'Selector de tono: casual / suave / brutalmente honesto (Premium)',
        'Tarjeta semanal de perspectivas con resumen personal',
        'VioRoast: roast basado en datos de tu semana (Premium)',
        'Voz TTS local en tu dispositivo (Premium)',
      ],
      vio: true,
    },
    'safe-call': {
      name: 'Llamada de Seguridad',
      shortDesc: 'Establece de antemano quién interviene – y una fecha límite para hacer check-in.',
      longDesc: 'Una red de seguridad discreta para encuentros con personas nuevas. Elige un contacto de confianza, establece una fecha límite y Roster te recuerda discretamente si guardas silencio — sin alboroto, sin drama.',
      bullets: [
        'Elige una persona y un contacto de confianza de tu agenda',
        'Establece una fecha límite con día y hora',
        'Cuenta atrás activa durante la sesión en curso',
        'Notificación discreta cuando vence el plazo',
        'Preparación de emergencia con un toque a tu contacto de confianza',
      ],
      icon: iconSafeCall,
    },
    notifications: {
      name: 'Notificaciones',
      shortDesc: 'Recordatorios discretos que saben cuándo aparecer – y cuándo no.',
      longDesc: 'Roster te avisa exactamente cuando es útil: cuando vence una prueba de ITS, se acerca una fecha límite de seguridad o una conexión ha estado en silencio un tiempo. Todo local, sin servidor push.',
      bullets: [
        'Control discreto cuando una conexión lleva demasiado tiempo en silencio',
        'Recordatorio de bienestar cuando vence una prueba',
        'Recordatorio de fecha límite de llamada de seguridad',
        'Deep-link directo a la vista relevante en la app',
        '100% local — sin servidor push, sin backend',
      ],
      icon: iconNotifications,
    },
    'vibe-radar': {
      name: 'Radar de Vibra',
      shortDesc: 'Un indicador silencioso por conexión – ve de un vistazo quién necesita atención ahora.',
      longDesc: 'El Radar de Vibra calcula un estado suave para cada conexión — soleado, nublado, lluvioso o silencio de radio — basado en el ritmo, el último contacto y tu propia valoración. Sin puntuaciones, solo una mirada honesta.',
      bullets: [
        'Cuatro niveles de estado: soleado / nublado / lluvioso / silencio de radio',
        'Basado en ritmo, último contacto y calidad de vibra',
        'Sensibilidad ajustable individualmente por persona',
        'Se puede activar y desactivar globalmente',
        'Aparece como indicador sutil directamente en la cuadrícula',
      ],
      icon: iconVibeRadar,
    },
  },
  da: {
    connections: {
      name: 'Forbindelser',
      shortDesc: 'Alle dine relationer ét sted – med relationstype, beskyttelsesstatus og en hurtig kontaktlog.',
      longDesc: 'Alle vigtige mennesker ét sted. For hver forbindelse kan du angive relationstype, safer-sex-status og hurtige noter — alt lokalt på din enhed, intet i skyen.',
      bullets: [
        'Persongitter med foto eller initialer og vibe-indikator',
        'Personlig velkomsthilsen – tilpasses tidspunktet på dagen',
        'Søgefelt og FAB til hurtigt at tilføje nye personer',
        'Swipe-gestus for at logge kontakt som "set i dag"',
        'Favoritmærkning til dine tættest forbindelser',
      ],
      icon: iconConnections,
    },
    'polycule-map': {
      name: 'Polycule Map',
      shortDesc: 'Dit relationenetværk som et levende kort. Du i centrum, alle forbindelser rundt om dig, farvekodede.',
      longDesc: 'Se dit netværk på et øjeblik. Polycule Map viser alle dine forbindelser som en interaktiv graf — dig i centrum, partnere og metamours rundt om dig, farvekodede efter relationstype.',
      bullets: [
        'Ego-netværk med koncentriske ringe',
        'Indre ring: tætte forbindelser – ydre ring: løsere',
        'Peer-buer for krydsforbindelser som metamour-relationer',
        'Nativ pan-zoom med knib-til-zoom-gestusser',
        'Tryk på en linje for at se forbindelsestypen',
      ],
      icon: iconPolyculeMap,
    },
    wellness: {
      name: 'Velvære',
      shortDesc: 'Hold styr på STI-tests og check-ins – diskret, lokalt, usynligt for alle andre end dig.',
      longDesc: 'Diskrete sundhedsnotater til ansvarlig relationspleje. Log STI-tests, safer-sex-samtaler og check-ins — krypteret på din enhed, usynligt for alle andre end dig.',
      bullets: [
        'Log STI-tests og sundheds-check-ins',
        'Næste forfaldne test med automatisk påmindelse',
        'Kronologisk tidslinje over alle poster',
        'Personfilter: alle eller én bestemt person',
        'Dyblink fra notifikationer direkte til check-in',
      ],
      icon: iconWellness,
    },
    reflection: {
      name: 'Refleksion',
      shortDesc: 'En dagbog til jalousi, compersion og alt derimellem. Til at sortere, ikke til at bedømme.',
      longDesc: 'En dagbog til alt, du ikke kan sætte ord på endnu. Jalousi, compersion, forvirring — lad det alt sammen bare være her, uden dom og uden algoritme.',
      bullets: [
        'Dekompressionsindlæg sorteret efter dato',
        'Detalje- og redigeringsvisning per indlæg',
        'Valgfrit link til en bestemt person',
        'Ingen scores, ingen algoritme – kun plads',
      ],
      icon: iconReflection,
    },
    insights: {
      name: 'Indsigt',
      shortDesc: 'Bløde mønstre frem for kolde tal: Hvor investerer du energi, hvor bliver det stille?',
      longDesc: 'Bløde mønstre frem for kolde tal. Indsigt viser dig, hvor du har investeret energi, og hvor det er blevet roligere — ingen scorer, kun ærlige observationer.',
      bullets: [
        'Ugeoverblik med automatisk nulstilling hver mandag',
        'Klikbare indsigter med personlig tilknytning til personer',
        'Vio-kort integreret (når Vio er aktiveret)',
        'Ingen scorer eller vurderinger – kun observationer',
      ],
      icon: iconInsights,
    },
    vio: {
      name: 'Vio',
      shortDesc: 'Din lille følgesvend, der spørger hvordan du har det – nogle gange blidt, nogle gange brutalt ærligt.',
      longDesc: 'Vio er din AI-følgesvend, der checker ind med dig hver dag. Tonen tilpasser sig: nogle gange let, nogle gange dybere. Alt forbliver på din enhed — Vio husker ingenting.',
      bullets: [
        'Samtaleflow: intro → højdepunkter → bekymringer → outro',
        'Tonevalg: afslappet / blid / brutalt ærlig (Premium)',
        'Ugentligt indsigts-kort med personligt overblik',
        'VioRoast: databaseret roast af din uge (Premium)',
        'Lokal TTS-stemme på din enhed (Premium)',
      ],
      vio: true,
    },
    'safe-call': {
      name: 'Sikkerhedsopkald',
      shortDesc: 'Beslut på forhånd hvem der griber ind – og en deadline for hvornår du checker ind.',
      longDesc: 'Et diskret sikkerhedsnet til møder med nye mennesker. Vælg en betroet kontakt, sæt en check-in-deadline, og Roster minder dig diskret hvis du tier stille — ingen drama.',
      bullets: [
        'Vælg en person og betroet kontakt fra din adressebog',
        'Sæt en check-in-deadline med dato og tid',
        'Aktiv nedtælling under en igangværende session',
        'Diskret notifikation når deadline udløber',
        'Nødberedskab med ét tryk til din betroede kontakt',
      ],
      icon: iconSafeCall,
    },
    notifications: {
      name: 'Notifikationer',
      shortDesc: 'Diskrete påmindelser, der ved hvornår de skal dukke op – og hvornår ikke.',
      longDesc: 'Roster minder dig præcis når det er nyttigt: når en STI-test forfalder, en sikkerhedsdeadline nærmer sig, eller en forbindelse har været stille for længe. Alt lokalt, ingen push-server.',
      bullets: [
        'Diskret tjek når en forbindelse har været stille for længe',
        'Velværepåmindelse når en test forfalder',
        'Sikkerhedsopkalds-deadline-påmindelse kort før udløb',
        'Dyblink direkte til den relevante visning i appen',
        '100% lokalt – ingen push-server, ingen backend',
      ],
      icon: iconNotifications,
    },
    'vibe-radar': {
      name: 'Vibe-Radar',
      shortDesc: 'En stille indikator per forbindelse – se med det samme hvem der har brug for opmærksomhed.',
      longDesc: 'Vibe-Radar beregner en blid status for hver forbindelse — solrig, overskyet, regnfuld eller radiotavshed — baseret på rytme, seneste kontakt og din egen vurdering. Ingen scorer, kun et ærligt blik.',
      bullets: [
        'Fire statusniveauer: solrig / overskyet / regnfuld / radiotavshed',
        'Baseret på rytme, seneste kontakt og vibe-kvalitet',
        'Individuelt justerbar følsomhed per person',
        'Kan slås til og fra globalt',
        'Vises som en subtil indikator direkte i persongitteret',
      ],
      icon: iconVibeRadar,
    },
  },
  sv: {
    connections: {
      name: 'Kopplingar',
      shortDesc: 'Alla dina relationer på ett ställe – med relationstyp, skyddsstatus och en snabb kontaktlogg.',
      longDesc: 'Alla viktiga personer på ett ställe. För varje koppling kan du ange relationstyp, safer sex-status och snabba anteckningar — allt lokalt på din enhet, inget i molnet.',
      bullets: [
        'Personrutnät med foto eller initialer och vibe-indikator',
        'Personlig hälsning som anpassas efter tid på dygnet',
        'Sökfält och FAB för att snabbt lägga till personer',
        'Svepgest för att logga kontakt som "träffat idag"',
        'Favoritmarkering för dina närmaste kopplingar',
      ],
      icon: iconConnections,
    },
    'polycule-map': {
      name: 'Polycule-karta',
      shortDesc: 'Ditt relationsnätverk som en levande karta. Du i centrum, alla kopplingar runt om dig, färgkodade.',
      longDesc: 'Se ditt nätverk på ett ögonblick. Polycule-kartan visar alla dina kopplingar som en interaktiv graf — du i centrum, partners och metamours runt om dig, färgkodade efter relationstyp.',
      bullets: [
        'Ego-nätverk med koncentriska ringar',
        'Inre ring: nära kopplingar – yttre ring: lösare',
        'Peer-bågar för korsförbindelser som metamour-relationer',
        'Nativ pan-zoom med nyp-till-zoom-gester',
        'Tryck på en linje för att se kopplingstypen',
      ],
      icon: iconPolyculeMap,
    },
    wellness: {
      name: 'Välmående',
      shortDesc: 'Ha koll på STI-tester och incheckarningar – diskret, lokalt, osynligt för alla utom dig.',
      longDesc: 'Diskreta hälsoanteckningar för ansvarsfull relationshantering. Logga STI-tester, safer sex-samtal och incheckarningar — krypterat på din enhet, osynligt för alla utom dig.',
      bullets: [
        'Logga STI-tester och hälsoincheckningar',
        'Nästa förfallna test med automatisk påminnelse',
        'Kronologisk tidslinje över alla poster',
        'Personfilter: alla eller en enskild person',
        'Djuplänk från notiser direkt till incheckning',
      ],
      icon: iconWellness,
    },
    reflection: {
      name: 'Reflektion',
      shortDesc: 'En dagbok för svartsjuka, compersion och allt däremellan. För att sortera, inte för att döma.',
      longDesc: 'En dagbok för allt du ännu inte kan sätta ord på. Svartsjuka, compersion, förvirring — låt allt vara här, utan domar och utan algoritm.',
      bullets: [
        'Dekompressionsanteckningar sorterade efter datum',
        'Detalj- och redigeringsvy per anteckning',
        'Valfri koppling till en specifik person',
        'Inga poäng, ingen algoritm – bara utrymme',
      ],
      icon: iconReflection,
    },
    insights: {
      name: 'Insikter',
      shortDesc: 'Mjuka mönster istället för kalla siffror: Var investerar du energi, var blir det tyst?',
      longDesc: 'Mjuka mönster istället för kalla siffror. Insikter visar var du har investerat energi och var det blivit tystare — inga poäng, bara ärliga observationer.',
      bullets: [
        'Veckosummering som automatiskt återställs varje måndag',
        'Klickbara insikter med personlig koppling till personer',
        'Vio-kort integrerat (när Vio är aktiverat)',
        'Inga poäng eller betyg – bara observationer',
      ],
      icon: iconInsights,
    },
    vio: {
      name: 'Vio',
      shortDesc: 'Din lille följeslagare som frågar hur det går – ibland mjuk, ibland lättsam, ibland brutalt ärlig.',
      longDesc: 'Vio är din AI-följeslagare som checkar in med dig varje dag. Tonen anpassar sig: ibland lättsam, ibland djupare. Allt stannar på din enhet — Vio minns ingenting.',
      bullets: [
        'Samtalsflöde: intro → höjdpunkter → bekymmer → outro',
        'Tonval: avslappnad / mjuk / brutalt ärlig (Premium)',
        'Veckokort med insikter och personlig överblick',
        'VioRoast: databaserad roast av din vecka (Premium)',
        'Lokal TTS-röst på din enhet (Premium)',
      ],
      vio: true,
    },
    'safe-call': {
      name: 'Säkerhetssamtal',
      shortDesc: 'Bestäm i förväg vem som ingriper – och en tidsgräns för när du checkar in.',
      longDesc: 'Ett diskret säkerhetsnät för möten med nya människor. Välj en betrodd kontakt, sätt en incheckningstidsgräns och Roster påminner diskret om du blir tyst — inga scener, ingen drama.',
      bullets: [
        'Välj en person och betrodd kontakt från din adressbok',
        'Sätt en incheckningstidsgräns med datum och tid',
        'Aktiv nedräkning under en pågående session',
        'Diskret notis när tidsgränsen löper ut',
        'Nödberedskap med ett tryck till din betrodda kontakt',
      ],
      icon: iconSafeCall,
    },
    notifications: {
      name: 'Notiser',
      shortDesc: 'Diskreta påminnelser som vet när de ska dyka upp – och när inte.',
      longDesc: 'Roster påminner dig exakt när det är användbart: när ett STI-test förfaller, en säkerhetstidsgräns närmar sig eller en koppling har varit tyst för länge. Allt lokalt, ingen push-server.',
      bullets: [
        'Diskret check när en koppling har varit tyst för länge',
        'Välmåendepåminnelse när ett test förfaller',
        'Säkerhetssamtals-tidsgränspåminnelse strax innan det löper ut',
        'Djuplänk direkt till relevant vy i appen',
        '100% lokalt – ingen push-server, ingen backend',
      ],
      icon: iconNotifications,
    },
    'vibe-radar': {
      name: 'Vibe-Radar',
      shortDesc: 'En tyst indikator per koppling – se på en sekund vem som behöver uppmärksamhet nu.',
      longDesc: 'Vibe-Radar beräknar en stilla status för varje koppling — solig, molnig, regnig eller radiotystnad — baserat på rytm, senaste kontakt och din egen bedömning. Inga poäng, bara en ärlig blick.',
      bullets: [
        'Fyra statusnivåer: solig / molnig / regnig / radiotystnad',
        'Baserat på rytm, senaste kontakt och vibe-kvalitet',
        'Individuellt justerbar känslighet per person',
        'Kan slås av och på globalt',
        'Visas som en subtil indikator direkt i personrutnätet',
      ],
      icon: iconVibeRadar,
    },
  },
};
